version: "3"

services:
  nginx:
    build: requirements/nginx
    ports:
        - 80:80
    volumes:
        - wp:/var/www/html
    depends_on:
        - wordpress
    restart: always
    networks:
      - net

  mariadb:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=123
    restart: always
    networks:
      - net
    volumes:
      - db:/var/lib/mysql

  wordpress:
    image: wordpress:4.7.1-php7.0-fpm
    volumes:
      - wp:/var/www/html
    networks:
      - net
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DB_NAME=wpdb
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_PASSWORD=123
    restart: always

volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vrogiste/data/wp
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/vrogiste/data/db

networks:
  net:
